Repository Go-Ride-Share/web-client, pull requests merged in 2024-10, with the labels that each got.

#18 Only show Post Ride button if user is logged in
  README.md
  src/components/Nav.js
  src/components/Nav.test.js
Labels: bug

#20 #2 - user can view their posts
  src/api-client/ApiClient.js
  src/components/Nav.js
  src/components/PageWithNav.js
  src/components/Post.js
  src/components/PostList.js
  src/components/PostList.test.js
  src/components/UserProfile.js
  src/components/UserProfile.test.js
  src/routes/ProtectedRoutes.js
Labels: enhancement

#38 Added Dockerfile
  Dockerfile
Labels: Feature
