Repository Go-Ride-Share/web-client, pull requests merged in 2024-11, with the labels that each got.

#41 Added Continuous Deployment
  .github/workflows/docker-publish.yml
Labels: enhancement

#44 Implement sprint 2 feedback
  src/api-client/ApiClient.js
  src/components/CreatePost.js
  src/components/Map.js
  src/components/Nav.js
  src/components/Nav.test.js
  src/components/PageWithNav.js
  src/components/Post.js
  src/components/PostList.js
  src/routes/ProtectedRoutes.js
Labels: enhancement

#49 Fix num seats
  src/components/SearchRides.js
Labels: bug

#50 Add favicon logo
  public/Favicon.ico
  public/Favicon.png
  public/manifest.json
  src/components/HomePage.js
Labels: enhancement

#52 Merge Sprint #3 into Main
  .github/workflows/azure-static-web-apps-salmon-bay-0bbe0cf0f.yml
  package-lock.json
  package.json
  public/Favicon.ico
  public/Favicon.png
  public/manifest.json
  src/App.js
  src/api-client/ApiClient.js
  src/api-client/ApiClient.test.js
  src/assets/images/google.svg
  src/components/ChatBox.js
  src/components/CreatePost.js
  src/components/HomePage.js
  src/components/Login.js
  src/components/Login.test.js
  src/components/Map.js
  src/components/Nav.js
  src/components/Nav.test.js
  src/components/PageWithNav.js
  src/components/Post.js
  src/components/PostList.js
  src/components/SearchRides.js
  src/routes/ProtectedRoutes.js
Labels: Feature

#53 Update azure-static-web-apps-black-rock-0cc860b0f.yml
  .github/workflows/azure-static-web-apps-black-rock-0cc860b0f.yml
Labels: bug
